Vinny/repo init
DISHDevEx/napp pull request #1
Opened 2023-04-12 18:24 UTC by vinayakSharm

Moving the following from openverso charts:
-Traffic Simulator
-Open5gs Values

Creating the following:
-Tests
-Workflows

2023-04-12 22:05 UTC, PaperArmada commented on tests/static_test_case_values.json
> +            "num_of_pings": 10000
Seems like a lot of (large) pings to be sending to a commercial site... Would using something like example.com from the AINA make more sense for this kind of load / testing? Why do we need this kind of volume?

2023-04-13 15:22 UTC, vinayakSharm commented on tests/static_test_case_values.json
> +            "num_of_pings": 10000
Hi matt,

(1) the file you are looking at here is the static test json **only for pytest** . This is only for testing purposes to create scripts. It does not actually trigger any UE's in the pytest module. 

(2) If we were to send a lot of (large/small) pings to websites that are not commercial grade they will not have the infrastructure to support our requests. They will most likely block us or shut down. 

(3) the actual json file to trigger UE's can be found at:https://github.com/DISHDevEx/napp/blob/vinny/repo-init/napp/traffic_simulator/test_case_values.json.  Here you will see that we are not just DDOS (ing) a single website. 

(4) all of these variables are modifible based on use case. There is no right or wrong answer, so you can change the webbsite and change the bitrate via json parameters.

2023-04-13 20:23 UTC, RemoNona commented on README.md
> +2. ensure your config file is set up correctly:
Capitalize 'ensure'. Add period at end.

2023-04-13 20:24 UTC, RemoNona commented on README.md
> +1. Update local kubectl config file:
These steps should probably end with something and that something should probably be a period unless you're listing something. In which case it'll be a colon.

2023-04-13 20:34 UTC, RemoNona commented on README.md
> +    ```
`Error from server (AlreadyExists): namespaces "openverso" already exists` - We should add a line saying that this if the namespace already exists, this error will show and can be ignored.

2023-04-13 20:35 UTC, RemoNona commented on README.md
> +    helm repo add openverso https://gradiant.github.io/openverso-charts/
If already added I get this output `"openverso" already exists with the same configuration, skipping`. Might be worth mentioning.

2023-04-13 20:36 UTC, RemoNona commented on README.md
> +    ```
`Error: INSTALLATION FAILED: cannot re-use a name that is still in use`

2023-04-13 20:41 UTC, RemoNona commented on README.md
> +
Perhaps a line about making sure to start with blank slate (and that it's okay to uninstall/delete everything). Perhaps add the commands to do so or link to those directions elswhere

2023-04-13 20:45 UTC, RemoNona commented on README.md
> +
I have 12 UE...

2023-04-13 20:45 UTC, RemoNona commented on README.md
> +    ```
This is showing me 12 UEs...

2023-04-13 20:49 UTC, RemoNona commented on README.md
> +    ```
This seems to continue pinging unless I `control C` - i think adding a line to letting the user know to do that would be helpful.

2023-04-13 20:54 UTC, RemoNona commented on README.md
> +    ```
This looks like it's reading the source code of google.com, is that correct? I think it would be useful to let the user know what output to expect with these three commands.

2023-04-13 20:55 UTC, RemoNona commented on README.md
> +
`exit`

2023-04-13 20:58 UTC, RemoNona commented on README.md
> +
Describe step.

Enter open5gs-mongodb bash.

2023-04-13 20:59 UTC, RemoNona commented on README.md
> +    ```
Describe step.

Open MongoDB by enter the following command.

2023-04-13 20:59 UTC, RemoNona commented on README.md
> +    ```
Describe step.

Switch database to `open5gs`.

2023-04-13 20:59 UTC, RemoNona commented on README.md
> +    ```
Describe step.

Print UE information.

2023-04-13 21:02 UTC, RemoNona commented on README.md
> +    ```
and again to `exit` another "layer" - not sure what to call it, but I had to `exit` twice

2023-04-13 21:04 UTC, RemoNona commented on README.md
> +### Network as App deployment (you have your EKS cluster and node group fired up):
(you have your EKS cluster and node group fired up) - is this what following the steps below will do or is this what you should have done up until this step. It's confusing, please clarify.

2023-04-13 21:06 UTC, RemoNona commented on README.md
> +    ```
At the end of following all the steps I see 10, so I am not sure what happened.

2023-04-13 21:10 UTC, RemoNona commented on tests/conftest.py
> +that can be reused throughout pytest without redefinition.
2-3 could be one line and it won't trip up pylint.

2023-04-13 21:17 UTC, RemoNona commented on tests/test_traffic_sim.py
> +    """
Generally speaking, I don't think we need docstrings for Pytest, as confimed by Praveen from my PR. But since this is a testkit I think it's useful. I would just format it to match the style we're following.

```
"""
Test if the population creation script correctly adds UEs with slice information.

Parameters
-----------
    tmp_path: Pytest fixture
        creates a temporary path that gets cleared post pytest.
    
    test_case_json: Pytest fixture
        json file that simulates the actual test case json used in the traffic simulation.

Outputs
--------
    None (Pytest)
"""
```

2023-04-13 21:19 UTC, RemoNona commented on tests/test_traffic_sim.py
> +    with open(test_file, "r") as read_file:
I believe it's best practice to .close() a file you open. This one does not get closed.

2023-04-13 21:19 UTC, RemoNona commented on tests/test_traffic_sim.py
> +    with open(test_file, "r") as read_file:
I believe it's best practice to .close() a file you open. This one does not get closed.

2023-04-13 21:21 UTC, RemoNona commented on tests/test_traffic_sim.py
> +    script_truth = None
I wonder if it's really necessary to declare this variable as None, then assign it the read_file.read().  I don't see the advantage, but maybe you can teach me.

Why not get rid of line 23, and use 25 only.

2023-04-13 21:21 UTC, RemoNona commented on tests/test_traffic_sim.py
> +    script_truth = None
Same thing in the other functions...

2023-04-13 21:24 UTC, RemoNona commented on tests/test_traffic_sim.py
> +    direct.mkdir()
There might be some commands I am unaware of here. Looks like in all three functions you create a temp directory. Is it actually making a **temporary** directory, or should you add a line to remove it the directory you create?

2023-04-13 21:25 UTC, RemoNona requested changes
Looking good. Please see comments. Thank you!

2023-04-13 22:25 UTC, vinayakSharm commented on .github/workflows/pytest-pr-check.yaml
> +on: ##define when this pytest will be run
done

2023-04-13 22:26 UTC, vinayakSharm commented on README.md
> +2. ensure your config file is set up correctly:
done

2023-04-13 22:27 UTC, vinayakSharm commented on README.md
> +1. Update local kubectl config file:
done

2023-04-13 22:33 UTC, vinayakSharm commented on README.md
> +    ```
done.

2023-04-13 22:34 UTC, vinayakSharm commented on README.md
> +    helm repo add openverso https://gradiant.github.io/openverso-charts/
pretty trivial. should be fine. thanks for the suggestion though. I am going to ignore.

2023-04-13 22:35 UTC, vinayakSharm commented on README.md
> +    ```
added section at the beginning that talks about using a fresh start. thanks!

2023-04-13 22:35 UTC, vinayakSharm commented on README.md
> +
yes sir, added to the top. did not write the comments, everyones installation requires differen uninstallation commands.

2023-04-13 22:39 UTC, vinayakSharm commented on README.md
> +    ```
done.

2023-04-13 22:39 UTC, vinayakSharm commented on README.md
> +    ```
ill double check

2023-04-13 22:40 UTC, vinayakSharm commented on README.md
> +    ```
double checked. I get 10. not sure how you got 12

2023-04-14 15:33 UTC, vinayakSharm commented on README.md
> +    traceroute -i uesimtun6 google.com
done

2023-04-14 15:33 UTC, vinayakSharm commented on README.md
> +    ```
done

2023-04-14 15:34 UTC, vinayakSharm commented on README.md
> +
done

2023-04-14 15:34 UTC, vinayakSharm commented on README.md
> +
done

2023-04-14 15:36 UTC, vinayakSharm commented on README.md
> +    ```
done

2023-04-14 15:36 UTC, vinayakSharm commented on README.md
> +    ```
done

2023-04-14 15:47 UTC, vinayakSharm commented on tests/test_traffic_sim.py
> +Module to contain all tests pertaining to traffic simulator
done.

2023-04-14 15:47 UTC, vinayakSharm commented on tests/test_traffic_sim.py
> +    """
thanks

2023-04-14 15:51 UTC, vinayakSharm commented on tests/test_traffic_sim.py
> +    with open(test_file, "r") as read_file:
"Using a with open() statement will automatically close a file once the block has completed"

https://www.learndatasci.com/solutions/python-close-file/#:~:text=Using%20a%20with%20open(),program%20is%20using%20the%20file.

2023-04-14 15:51 UTC, vinayakSharm commented on tests/test_traffic_sim.py
> +    with open(test_file, "r") as read_file:
"Using a with open() statement will automatically close a file once the block has completed"

https://www.learndatasci.com/solutions/python-close-file/#:~:text=Using%20a%20with%20open(),program%20is%20using%20the%20file.

2023-04-14 15:55 UTC, vinayakSharm commented on tests/test_traffic_sim.py
> +    script_truth = None
done

2023-04-14 15:56 UTC, vinayakSharm commented on tests/test_traffic_sim.py
> +    direct.mkdir()
yes during pytest run in pr, the github workflows will create a docker environment that gets shutdown after use. The temp directory will be wiped.

2023-04-14 19:54 UTC, vinayakSharm commented on tests/test_traffic_sim.py
> +    with open(test_file, "r") as read_file:
"Using a with open() statement will automatically close a file once the block has completed"

https://www.learndatasci.com/solutions/python-close-file/#:~:text=Using%20a%20with%20open(),program%20is%20using%20the%20file.

2023-04-14 20:10 UTC, RemoNona approved these changes

2023-04-14 21:29 UTC, merged